" Environment {{{
    set nocompatible
    scriptencoding utf-8
    set termencoding=utf-8
    set autochdir
    " Directories {
        silent execute '!mkdir -p $HOME/.vim/tmp/{backup,swap,view,undo}'
        set backupdir=$HOME/.vim/tmp/backup/
        set backup
        set directory=$HOME/.vim/tmp/swap/
        set viewdir=$HOME/.vim/tmp/view/
        set undodir=$HOME/.vim/tmp/undo/
        " store undo files, undo edits after deleting a buffer
        set undofile
        set viminfo='50,n$HOME/.vim/tmp/viminfo
    " }
" }}}
" Bundles {{{
    " TODO:
    " 1. clone vundle into ~/.vim/bundle/vundle
    " 2. add here: filetype off
    " 3. add here: set rtp+=~/.vim/bundle/vundle/
    " 4. add here: call vundle#rc()
    " 5. add here: Bundle 'gmarik/vundle'
    " 6. add here further bundles and a little documentation above each
    "    Bundle instruction, so you can remember what each bundle is for
    " 7. add here: Helptags
    " 8. add here: filetype plugin indent on
    " 9. In each section below, add corresponding customizations as required
    "    for that bundle, pinpointing each time which bundle the
    "    configuration belongs to.
    "    For instance, the 'janson/bufonly.vim' bundle could deserve an entry
    "    in the 'Maps' section further down below for the :BufOnly command.
    "    Other bundles could need different configurations spread throughout
    "    different sections.
    "    The most important thing here is to document your vimrc. One may
    "    be unused to this, but since vim is such a powerful editor ...
    "    WITH GREAT POWER COMES GREAT RESPONSIBILITY
" }}}
" Editing {{{
    set tabstop=8
    set shiftwidth=4
    set softtabstop=4
    set expandtab
    set autoindent
" }}}
" Visuals {{{
    set visualbell
    set title
    syntax on
    set relativenumber
    set modeline
    set showmode
    set showcmd
    set showmatch
    set incsearch
    set hlsearch
    set wildmenu
    set wildmode=list:longest,full
    set list
    set listchars=tab:▸\ ,eol:¬
    set showbreak=↪
    set ttyfast
    set ruler
    set textwidth=80
    set wrapmargin=80
    set formatoptions=qrn1
    set colorcolumn=80
    set splitright splitbelow
    set shortmess+=afilmnrxoOtT
    set viewoptions=folds,options,cursor,unix,slash
    " Coloring {
        colors elflord
        highlight Folded term=standout ctermfg=0 ctermbg=7 guifg=Black guibg=ivory3
        highlight WhitespaceEOL ctermbg=Red guibg=Red
        match WhitespaceEOL /\s\+$/
    " }

" }}}
" Maps {{{
    " Use <Leader> in maps, so it's easier to share them, yet still allow
    " anyone to use them in their own, personalized way. Remember, not all
    " keyboards have US layout.
    let mapleader=','

    " Force yourself to learn proper vim {
        nnoremap <UP> <NOP>
        nnoremap <DOWN> <NOP>
        nnoremap <LEFT> <NOP>
        nnoremap <RIGHT> <NOP>
        inoremap <UP> <NOP>
        inoremap <DOWN> <NOP>
        inoremap <LEFT> <NOP>
        inoremap <RIGHT> <NOP>
        vnoremap <UP> <NOP>
        vnoremap <DOWN> <NOP>
        vnoremap <LEFT> <NOP>
        vnoremap <RIGHT> <NOP>
    " }
" }}}
" vim:set foldmarker={{{,}}} foldlevel=0 foldmethod=marker:
